import type { Metadata } from "next";
import { inter } from "@/lib/fonts";
import "@/app/globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={clsx("h-full antialiased", inter.className)}>{children}</body>
    </html>
  );
}
